version: '3.8'
services:
    db:
        image: postgres
        restart: always
        ports:
            - 5434:5432
        environment:
            POSTGRES_USER: guest
            POSTGRES_PASSWORD: guest
            POSTGRES_DB: time_tracker