spring:
  application:
    name: TimeTracker
  datasource:
    url: jdbc:postgresql://localhost:5434/time_tracker
    username: guest
    password: guest
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        hbm2ddl:
          auto: update
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: public
  token:
    signing-key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855

